# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-17 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoAdminAccessIPWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitelist_reason', models.CharField(help_text=b'Reason for the whitelist?', max_length=255)),
                ('ip', models.CharField(help_text=b'Enter an IP to whitelist', max_length=255)),
            ],
            options={
                'db_table': 'django_admin_access_ip_whitelist',
                'verbose_name': 'Django /admin access IP whitelist',
                'verbose_name_plural': 'Django /admin access allowed IPs',
                'permissions': (('can_whitelist_user', 'Can Whitelist User'),),
            },
        ),
    ]
